### ISSUE TITLE
Unable to build with Carthage on Xcode 13.2++

### ISSUE THREAD

**Issue by SSenocico** [Henryforce/BLECombineKit#32]
Hi,
When run `carthage update`, receive:

```
*** Fetching BLECombineKit
*** Checking out BLECombineKit at "v0.1.7"
*** xcodebuild output can be found in /var/folders/70/r33z6h3x10n3bqxr45td4j080000gn/T/carthage-xcodebuild.4P67hs.log
*** Building scheme "BLECombineKit" in BLECombineKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/x/Documents/Programming/ASSIST/NDSports/Carthage/Checkouts/BLECombineKit/BLECombineKit.xcodeproj -scheme BLECombineKit -configuration Release -derivedDataPath /Users/x/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2.1_13C100/BLECombineKit/v0.1.7 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/70/r33z6h3x10n3bqxr45td4j080000gn/T/BLECombineKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/x/Documents/Programming/ASSIST/NDSports/Carthage/Checkouts/BLECombineKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/70/r33z6h3x10n3bqxr45td4j080000gn/T/carthage-xcodebuild.4P67hs.log
```

I was thinking that this was related to this Carthage issue:
https://github.com/Carthage/Carthage/issues/3019
But not, is not related. The error is always the same.

Any help?

**Comment by Henryforce** [comment]
Thanks for submitting the issue. I have been looking into it and the Carthage logs provide some insights:
```
The following build commands failed:
	CompileSwift normal armv7 (in target 'CombineExt' from project 'CombineExt')
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'CombineExt' from project 'CombineExt')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'CombineExt' from project 'CombineExt')
```
[CombineExt](https://github.com/CombineCommunity/CombineExt) seems to be stable but somehow the build is not compiling on Carthage and only in SPM... This is one good point to start the research on why the build fails.
While we try to find a solution, I will be updating the project README to remove temporal Carthage support in order to avoid further confusion. 
If you happen to have some extra time to help us investigate, that would be amazing as well.

**Comment by SSenocico** [comment]
Thank you very much! 🎉

**Comment by SSenocico** [comment]
Thank you very much @Henryforce 🥳
It worked flawlessly.

For the user that may encounter Carthage compilation errors: 
- check this post:
https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506
