### ISSUE TITLE
Observe the received AdvertisementData from the connected device

### ISSUE THREAD

**Issue by SSenocico** [Henryforce/BLECombineKit#36]
Hi,
This is not really an issue, but rather a question.
I'm trying to observe via Combine the received **advertisementData** from the connected device.

I don't know exactly how to achieve it, because the observable **didDiscoverAdvertisementData** is internal, so I don't have access to it.

![Screenshot 2022-02-24 at 16 01 00](https://user-images.githubusercontent.com/60232541/155538491-c1ae03ef-cb9f-4705-99b2-e7505c885bd4.png)

I also conformed to the **CBCentralManagerDelegate** 
`manager = BLECombineKit.buildCentralManager(with: CBCentralManager(delegate: self, queue: nil))`
and implement the 
`func centralManager(_ central: CBCentralManager, didDiscover peripheral: CBPeripheral, advertisementData: [String : Any], rssi RSSI: NSNumber)` method, but it is never called. 

Can you give me a clue please?
Thanks a lot!

**Comment by Henryforce** [comment]
Hello @SSenocico , sorry for the late reply!

The delegate is intended to be used internally. 

If you want to read the advertisement data you can simply do something like this:

```
centralManager.scanForPeripherals(withServices: nil, options: nil) // NOTE: don't forget to declare this variable
.sink(receiveCompletion: { completion in
        print(completion)
    }, receiveValue: { scanResult in
        print(scanResult) // BLEScanResult
    })
    .store(in: &disposables) // NOTE: don't forget to declare the disposables variable!
```

BLEScanResult has a property containing the Advertisement Data:
https://github.com/Henryforce/BLECombineKit/blob/master/Source/Central/BLEScanResult.swift

I hope it helps!
