### ISSUE TITLE
Doesn't build for MacOS

### ISSUE THREAD

**Issue by fodormarton** [Henryforce/BLECombineKit#6]
`CBCentralManagerWrapper:74`
 'registerForConnectionEvents(options:)' is unavailable in macOS

**Comment by fodormarton** [comment]
Weird, cause I've just cloned the repo, built BLECombineKit for Mac and it seems to be fine in local. I've got the above issue when imported it as a Swift Module dependency in another project and trying to build for mac. Any thoughts?

**Comment by Henryforce** [comment]
Hey @fodormarton ! Thanks for the interest on BLECombineKit and sorry for the late reply! It seems the issue you are facing with your project when using SPM is your minimum iOS/MacOS support. If you look at the docs for 'registerForConnectionEvents(options:)' , you will see that it is supported only from iOS 13+, Mac OS 11+ . Could you verify the minimum OS support in your project? Take a look to the docs for that function: https://developer.apple.com/documentation/corebluetooth/cbcentralmanager/3174844-registerforconnectionevents

**Comment by Henryforce** [comment]
I just updated the README with the information on minimum OS support for BLECombineKit
